version: "3.9"
services:

  user-service:
    image: "user-service:1.0.0"
    container_name: user-service
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "500M"
    volumes:
      - ./logs:/logs
    ports:
      - "8083:8080"
      - "9093:9090"

  project-service:
    image: "project-service:1.0.0"
    container_name: project-service
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "500M"
    volumes:
      - ./logs:/logs
    ports:
      - "8084:8080"
      - "9094:9090"

  issue-service:
    image: "issue-service:1.0.0"
    container_name: issue-service
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "500M"
    volumes:
      - ./logs:/logs
    ports:
      - "8085:8080"
      - "9095:9090"