
apiVersion: 1

datasources:
  - name: local-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true
  - name: local-loki-datasource
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
  - name: local-loki-as-prometheus-datasource
    type: prometheus
    access: proxy
    url: http://loki:3100/loki
    editable: true
